get:
  operationId: getGrafanaNetworks
  tags:
  - Grafana
  summary: Get Grafana networks dashboard
  parameters:
  - $ref: ../../components/parameters/dataCenter.yaml
  responses:
    '200':
      description: Get Grafana networks dashboard
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/GetGrafanaDashboardLinkResponse.yaml
          examples:
            example:
              summary: Grafana networks dashboard link
              value:
                code: 200
                data:
                  link: http://example-data-center/grafana/d/Xx2kkftWk/network?orgId=1&refresh=5m
                  enabled: true
                msg: fetch top network link successfully
                status: ok
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 401
              msg:
                type: string
                example: 'invalid_grant: Invalid user credentials'
              status:
                type: string
                example: unauthorized
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 500
              msg:
                type: string
                example: 'failed to get Grafana networks dashboard: internal server
                  error'
              status:
                type: string
                example: internal server error
