get:
  operationId: getGrafanaTopHosts
  tags:
  - Grafana
  summary: Get Grafana top hosts dashboard
  parameters:
  - $ref: ../../components/parameters/dataCenter.yaml
  responses:
    '200':
      description: Get Grafana top hosts dashboard
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/GetGrafanaDashboardLinkResponse.yaml
          examples:
            example:
              summary: Grafana top hosts dashboard link
              value:
                code: 200
                data:
                  link: http://example-data-center/grafana/d/M3ncw6lmk/top-hosts?refresh=5m&kiosk=tv&orgId=1
                  enabled: true
                msg: fetch top host link successfully
                status: ok
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 401
              msg:
                type: string
                example: 'invalid_grant: Invalid user credentials'
              status:
                type: string
                example: unauthorized
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 500
              msg:
                type: string
                example: 'failed to get Grafana top hosts dashboard: internal server
                  error'
              status:
                type: string
                example: internal server error
